"""Creates modules

Revision ID: 181b7f97cbc9
Revises: 276b4d0abe43
Create Date: 2024-04-07 20:13:52.021466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181b7f97cbc9'
down_revision = '276b4d0abe43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photographers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('portfolio_pictures', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['photographers.id'], name=op.f('fk_users_photographer_id_photographers')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('photoshoots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['photographers.id'], name=op.f('fk_photoshoots_photographer_id_photographers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_photoshoots_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photoshoots')
    op.drop_table('users')
    op.drop_table('photographers')
    # ### end Alembic commands ###
